version: "3.9"
services:
  web:
    container_name: geesome
    build: .
    command: npm start
      - "5000:5000"
    depends_on:
      - ipfs
  ipfs:
    container_name: go_ipfs
    image: "ipfs/go-ipfs"
    expose:
      - "5001"
      - "4001"
      - "8080"
    volumes:
      - "${STORAGE_STAGING}:/export"
      - "${STORAGE_DATA}:/data/ipfs"