version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  ipfs:
    image: "ipfs/go-ipfs"
    ports:
      - "5001:5001"
      - "4001:4001"
      - "8080:8080"
    volumes:
      - "${STORAGE_STAGING}:/export"
      - "${STORAGE_DATA}:/data/ipfs"